### ISSUE TITLE
Icon names aren't lining up

### ISSUE THREAD

**Issue by Daemach** [hawkeye64/iconexplorer.app#13]
I really like this app.  I was searching for a gift icon, and it came up with one (inset window).  When I tried using the icon name (matCardGiftcard) in my app, it broke.  I then went to the quasar docs for icon, followed the material design link, searched for gift again and got the outer set that used card_giftcard and redeem, both of which worked.

https://www.screencast.com/t/Sd7UqUJ8

Also, copying the button code yields the below text which breaks by default because matCardGiftcard is not defined.  I think it should be icon="" without the colon.
```
<q-btn :icon="matCardGiftcard" />
```

**Comment by hawkeye64** [comment]
@Daemach On your image, that is the name of the icon when using the webfont (woff, woff2).

In order to get the icon to work, you have to import it:

```js
import { matCardGiftcard } from '@quasar/extras/material-icons'
```

**Comment by hawkeye64** [comment]
If you didn't know, you can have the Icon Explorer create your imports for you.

**Comment by Daemach** [comment]
I didn’t know.  It would be good to add all of that info somewhere. Great
tool!

**Comment by hawkeye64** [comment]
Thanks. If you have any thoughts where the info can be added in listening.

**Comment by Daemach** [comment]
https://www.screencast.com/t/CxNaqkIwSxor

FWIW, since the same icon exists in the default material icons that are
already included (using the webfont), it would be great to use those and
only import where absolutely necessary.

**Comment by hawkeye64** [comment]
Looks nice. You may not also know that if you add several icons to the `library` and then click the cart icon, you can create imports for all of them:

![image](https://user-images.githubusercontent.com/10262924/144635413-2abb2d8a-d86c-430f-a04a-44aec3235cc4.png)

Then click the `Imported` button and paste directly into your code:

```js
import { matAddAPhoto, matAddAlert, matAddShoppingCart } from '@quasar/extras/material-icons'
import { antOutlinedAudioMuted, antOutlinedAudio } from 'quasar-extras-svg-icons/ant-design-icons'
```

**Comment by hawkeye64** [comment]
> FWIW, since the same icon exists in the default material icons that are already included (using the webfont), it would be great to use those and only import where absolutely necessary.

Yes, but that's not how it is done in quasar/extras. I am following the same conventions. This is so that QIcon can determine if it is a font or SVG icon. There are different protocols at play here where it has to make decisions.
