### ISSUE TITLE
[Bug] No result message shows up, although there are results (when icon set is selected)

### ISSUE THREAD

**Issue by smolinari** [hawkeye64/iconexplorer.app#14]
Hi,

At the initial start of the app, if I type in one thing and get results, I get the button selections for the icon sets with results. Cool! However, if I undo that search and start again, then it shows, correctly, other icon sets, but also shows the no results message at the bottom, which it shouldn't. 

![image](https://user-images.githubusercontent.com/3314957/145248159-d30a1510-e4fc-4513-9635-8ea4bec41c50.png)

Scott

**Comment by hawkeye64** [comment]
@smolinari For the second part, what do you think of this when the results don't have a match for the currently selected icon set?
![image](https://user-images.githubusercontent.com/10262924/145250034-67df3667-c31f-4957-b7b5-2b1f2086a5b1.png)

I'll address the first part shortly.

**Comment by hawkeye64** [comment]
When there is no icon set selected and no matches for the filter, you will no see this:

![image](https://user-images.githubusercontent.com/10262924/145259232-a6ae46e6-d8a5-47af-ba60-ac05b013b893.png)

**Comment by hawkeye64** [comment]
Fix in new release (but available now when built on Netlify)

**Comment by smolinari** [comment]
@hawkeye64 - I didn't even get past the initial startup and search. But, if an icon set is selected and a new search is done, and nothing is found in that selected icon set, the suggestion above to show there aren't any in the icon set is good. 

This issue was started, because if I searched for something and there were icon sets found, the buttons would show to select from. If I change the search entry without any selection, then I got the "No icons found that match the filter". I should have just gotten the new set of selection buttons. 

I tested again. "No Icons Found" isn't true on the first search. I get a lot of icon set selections from the search. The message should be "Icons found, select an icon set above to peruse the results in each set." or something to that effect. Or, don't show any message, as it was before. 

Scott

**Comment by hawkeye64** [comment]
Yes, eventually there will be instructions on the main page when you arrive.

Also, sometimes the message will show up because the message is taking too long. I need to set a var so a spinner can appear while the search is happening.

**Comment by hawkeye64** [comment]
I just released v2.4.0 - this should satisfy all of your concerns @smolinari . 
If you find anything further, do not hesitate to create an issue. Thanks.

**Comment by smolinari** [comment]
Good job @hawkeye64 !!! 👍 

Scott
